logging:
  level:
    root: INFO

integrations:
  kafka-topic:
    consumer: "out_store.shop_store.products_info"
    producer: "shop_store.out_store.products_info"
  external:
    product-service:
      url: "${EXTERNAL_GET_PRODUCT_URL}"

spring:
  application:
    name: store
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:store
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: embedded
      platform: h2
  kafka:
    bootstrap-servers: kafka:9093 # docker container
#    bootstrap-servers: localhost:9092 # локальный запуск
    consumer:
      group-id: my-consumer-store-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.technical.store.deserializer.ProductDtoJsonListDeserializer
      max-poll-records: 1
      properties:
        max.poll.intervals.ms: 600000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  error:
    whitelabel:
      enabled: false
